# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  config.vm.box_check_update = false
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end
  config.ssh.insert_key = false
  config.vm.provision "shell", inline: <<-SHELL
    set -e

    rm -rf /etc/yum.repos.d/CentOS-*.repo 2>/dev/null || true
    curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo

    yum clean all
    yum makecache

    yum install ansible -y
  SHELL
end
