# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.hostname = "node1"
  config.vm.network "private_network", ip: "10.0.0.1"

  config.ssh.insert_key = false

  config.vm.provision "shell", name: "disable_swap", path: "00_disable_swap.sh"
  config.vm.provision "shell", name: "disable_selinux", reboot: true, path: "01_disable_selinux.sh"
  config.vm.provision "shell", name: "setup_root_ssh", path: "02_setup_root_ssh.sh"

  # config.vm.provision "shell", name: "install_containerd", path: "03_install_containerd.sh"
  # config.vm.provision "shell", name: "install_kubernetes", path: "04_install_kubernetes.sh"
  # config.vm.provision "shell", name: "install_etcd", path: "05_install_etcd.sh"

  config.vm.provision "shell", name: "generate_ca_root", path: "06_generate_ca_root.sh"
  config.vm.provision "shell", name: "generate_ca_root_config", path: "07_generate_ca_root_config.sh"
  config.vm.provision "shell", name: "generate_ca_etcd", path: "08_generate_ca_etcd.sh"
  config.vm.provision "shell", name: "generate_ca_etcd_config", path: "09_generate_ca_etcd_config.sh"
  config.vm.provision "shell", name: "generate_ca_etcd_server", path: "10_generate_ca_etcd_server.sh"
  config.vm.provision "shell", name: "generate_ca_etcd_peer", path: "11_generate_ca_etcd_peer.sh"
end
