[nodes]
node1 ansible_host=10.0.0.101
node2 ansible_host=10.0.0.102
node3 ansible_host=10.0.0.103

[ca]
node1

[etcd]
node1
node2
node3

[apiserver]
node1
node2

[kubelet]
node1
node2
node3

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_python_interpreter=/usr/bin/python2
